"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tmrm = require("azure-pipelines-task-lib/mock-run");
const path = require("path");
let taskPath = path.join(__dirname, '..', 'index.js');
let tmr = new tmrm.TaskMockRunner(taskPath);
tmr.setInput('method', 'get');
tmr.setInput('urlSuffix', '/api/now/table/incident');
process.env['username'] = 'admin';
process.env['password'] = 'FfB7dW=*k7Bf';
process.env['host'] = 'https://dev75028.service-now.com';
tmr.run();
